/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
      "./src/**/*.{js,ts,jsx,tsx,mdx}",
      "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
      "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
      "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    ],
    safelist: [
      // Critical classes for roadmap component
      'w-full',
      'px-4',
      'py-6',
      'mb-6',
      'text-2xl',
      'font-bold',
      'text-gray-800',
      'text-center',
      'py-8',
      'bg-gray-50',
      'rounded-lg',
      'border',
      'border-gray-200',
      'text-gray-500',
      'text-sm',
      'text-gray-400',
      'mt-2',
      'relative',
      'absolute',
      'left-1/2',
      'transform',
      '-translate-x-1/2',
      'h-full',
      'w-1',
      'bg-blue-200',
      'z-0',
      'z-10',
      'flex',
      'flex-col',
      'md:flex-row',
      'mb-10',
      'items-center',
      'justify-center',
      'w-6',
      'h-6',
      'rounded-full',
      'shadow',
      'bg-green-500',
      'bg-blue-500',
      'md:flex-row-reverse',
      'md:w-1/2',
      'p-6',
      'justify-between',
      'items-start',
      'mb-2',
      'text-xl',
      'mb-4',
      'font-semibold',
      'gap-2',
      'bg-gray-100',
      'text-gray-800',
      'px-2',
      'py-1',
      'text-xs',
      'space-y-2',
      'text-blue-600',
      'hover:text-blue-800',
      'mr-2',
      'ml-2',
      'text-green-600',
      'hidden',
      'md:block',
      // Professional Theme Classes
      'backdrop-filter',
      'backdrop-blur-md',
      'backdrop-blur-lg',
      // Teal color classes (primary)
      'from-teal-600',
      'to-teal-800',
      'from-teal-700',
      'to-teal-900',
      'from-teal-800',
      'to-teal-950',
      'text-teal-50',
      'text-teal-100',
      'text-teal-700',
      'text-teal-800',
      'text-teal-900',
      'bg-teal-50',
      'bg-teal-100',
      'bg-teal-700',
      'bg-teal-800',
      'bg-teal-900',
      'border-teal-200',
      'border-teal-300',
      'border-teal-700',
      'hover:bg-teal-800',
      'hover:text-teal-100',
      'hover:from-teal-700',
      'hover:to-teal-900',
      'shadow-teal-500/20',
      'shadow-teal-500/30',
      // Amber color classes (secondary)
      'from-amber-500',
      'to-amber-600',
      'from-amber-600',
      'to-amber-700',
      'text-amber-50',
      'text-amber-600',
      'text-amber-700',
      'text-amber-800',
      'bg-amber-50',
      'bg-amber-100',
      'bg-amber-600',
      'bg-amber-700',
      'border-amber-200',
      'border-amber-600',
      'hover:bg-amber-700',
      'hover:from-amber-600',
      'hover:to-amber-700',
      'shadow-amber-500/30',
      // Attribute colors
      'bg-blue-500',
      'bg-violet-500',
      'bg-red-500',
      'bg-emerald-500',
      'bg-indigo-500',
      'bg-orange-500',
      'text-blue-500',
      'text-violet-500',
      'text-red-500',
      'text-emerald-500',
      'text-indigo-500',
      'text-orange-500',
      // Slate UI colors
      'bg-slate-50',
      'bg-slate-100',
      'bg-slate-200',
      'bg-slate-700',
      'border-slate-200',
      'border-slate-300',
      'text-slate-600',
      'text-slate-700',
      'text-slate-800',
      // Gradient backgrounds
      'bg-gradient-to-r',
      'bg-gradient-to-b',
      'bg-gradient-to-br',
      // Animation classes
      'animate-fade-in',
      'animate-slide-in',
      'animate-progress',
      'transition-all',
      'duration-300'
    ],
    theme: {
      extend: {
        fontFamily: {
          'inter': ['Inter', 'sans-serif'],
          'source': ['"Source Sans Pro"', 'sans-serif']
        },
        animation: {
          'fade-in': 'fadeIn 0.5s ease-out',
          'slide-in': 'slideIn 0.3s ease-out',
          'progress': 'progress 1s ease-out',
          'pulse-subtle': 'pulse-subtle 3s ease-in-out infinite alternate'
        },
        keyframes: {
          fadeIn: {
            '0%': { opacity: 0 },
            '100%': { opacity: 1 }
          },
          slideIn: {
            '0%': { transform: 'translateY(10px)', opacity: 0 },
            '100%': { transform: 'translateY(0)', opacity: 1 }
          },
          progress: {
            '0%': { width: '0%' },
            '100%': { width: '100%' }
          },
          'pulse-subtle': {
            '0%, 100%': { 
              opacity: 1,
              boxShadow: '0 0 8px 1px rgba(15, 118, 110, 0.2)'
            },
            '50%': { 
              opacity: 0.9,
              boxShadow: '0 0 12px 3px rgba(15, 118, 110, 0.3)'
            }
          }
        },
        backdropBlur: {
          'xs': '2px',
        },
        boxShadow: {
          'card': '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -2px rgba(0, 0, 0, 0.05)',
          'card-hover': '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -4px rgba(0, 0, 0, 0.05)',
          'button': '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
          'button-hover': '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)'
        },
        transitionDuration: {
          '2000': '2000ms',
          '3000': '3000ms',
        }
      },
    },
    plugins: [],
  };