/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
      "./src/**/*.{js,ts,jsx,tsx,mdx}",
      "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
      "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
      "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    ],
    safelist: [
      // Critical classes for roadmap component
      'w-full',
      'px-4',
      'py-6',
      'mb-6',
      'text-2xl',
      'font-bold',
      'text-gray-800',
      'text-center',
      'py-8',
      'bg-gray-50',
      'rounded-lg',
      'border',
      'border-gray-200',
      'text-gray-500',
      'text-sm',
      'text-gray-400',
      'mt-2',
      'relative',
      'absolute',
      'left-1/2',
      'transform',
      '-translate-x-1/2',
      'h-full',
      'w-1',
      'bg-blue-200',
      'z-0',
      'z-10',
      'flex',
      'flex-col',
      'md:flex-row',
      'mb-10',
      'items-center',
      'justify-center',
      'w-6',
      'h-6',
      'rounded-full',
      'shadow',
      'bg-green-500',
      'bg-blue-500',
      'md:flex-row-reverse',
      'md:w-1/2',
      'p-6',
      'justify-between',
      'items-start',
      'mb-2',
      'text-xl',
      'mb-4',
      'font-semibold',
      'gap-2',
      'bg-gray-100',
      'text-gray-800',
      'px-2',
      'py-1',
      'text-xs',
      'space-y-2',
      'text-blue-600',
      'hover:text-blue-800',
      'mr-2',
      'ml-2',
      'text-green-600',
      'hidden',
      'md:block'
    ],
    theme: {
      extend: {},
    },
    plugins: [],
  };